version: "2.4"

networks:
  software-config:
    name: network-config-server
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
services:
  ms-config-server:
    image: ms-config_server:0.0.1
    mem_limit: 150m
    ports:
      - "8889:8889"
    networks:
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.2:9411"
      - "EUREKA_URI=http://ms-discovery:8762/eureka"
    volumes:
      - "/opt/local:/opt/arqutectura/logs"