spring:
  application:
    name: ms-config_server
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Micro-Servicios/micro-servicio
          default-label: "main"

server:
  port: 8889
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}