spring:
  application:
    name: ms-config_server
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/Micro-Servicios/micro-servicio
          default-label: "main"

          uri: git@github.com:Micro-Servicios/micro-servicio.git
          ignoreLocalSshSettings: true
          hostKey: "AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          hostKeyAlgorithm: ssh-rsa
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIG4wIBAAKCAYEAsquoDlieQEJpDq6rTQEptxs3T0hMFbWf/G64UJTYk9VQw8si
            gImLeTigHjaq3+Mrj02frh9oZH2L4k4pMjzjruJaPMC0OoAKZRK2ku6CxGQqlihh
            PbgBe5Fs7T1UY1W5KiPaKaY9c+P3yOGoCmcncGuHDnvpv4cbdpDxWAMwmSbkLLFN
            STKUsHxjvS8Q7Txw5f+AM/cS6+SeA4kYmKTRcoaBPa642sJH/yIPW/XEo/+hjwkD
            EToWSKCUXMtIjDI0GzlrFNy6yaTWWx5Zor6ZTmZUh/b08BKR9qqSg2I1MSTBHL6E
            gq4SkxYa8k735ajNB+jsWWaP0eabXmpqkmshCAeruPxkjVZFA1lWkxudx2Bdjk6u
            vwcAjEYKKy2T5yfSmPU1sd+8aWT31+hCgFLtdBnpjyQ4Uibysyl/rFEEyYwcWCMo
            iznjRof26KxgO5Rzowvnq4Gx4ArVzgvoNIKJFCcQjfj7wM2CW66xt573iEsc3wCP
            YvdP9pcn9428e5kHAgMBAAECggGAXUJ8VgCrmZ8Qdzl08JzKyWjLVfbGwA4tk/W2
            /1iyM3gE0C4XtEAXLQ8BhMPELVjGQ+agkqKSOuHNQjLKDg76SS6dK1jquh5bTqaV
            5dvZJemi0P4Cw9Rn8bfWw35frfnwzK4qEdNUAEnd7Fzc+ZEeZO+7bzP+rpo3G4xM
            bUQ8+bPzJeDmFm7wba5/4R/QFgSWaXcT1AwDNF4AnJfS3too+T5791Zb5tPCAMom
            ejmuimvESITLtRI8z2wCBO2W0Jbi/ILcbMXpB0gxb6Omc0fIBnxe06lndxRrZRT0
            mcmFntJYE3UjNntUkIF3RuiA8PONIdkY1lM54TKzdi36w1oSija5L25Fo6w3SZ/g
            X05f2khkTtHKxgFCXCjyLbsPANjVTsR7mM+MTnp7G7CQzhXa2l6qsLGyfYkqBbOs
            M/UmeGBJn7LMZWZxSN6wjvhBZdJMCJW9MiXd2uDGhKmc/10gb4CYi5MbaV7aF35B
            CwI78oAyfHkPtR18Ll1lBgXkJt8BAoHBANo864zjsRQpm7EUabF9seyfiTbnTb3i
            1c1/00twZ3ixi0kpWnkqiuBmKmIztZUrR70HrpG4PMAfztJcS1+WGHNR/17z9Mys
            vRvYro+iv6ZBqKE0ztq12tISMJSIigDxdOC7hpDt2hkjni7ub+aAHaJk7SvplzXB
            9k3zjklQ6UAfj2UvTQBwNNBAITYbYkTHiP507F7B+yTb9E/3Z2sqFa4QrQbmSZJc
            eBXUPQefahgAtNCyyuJwydT4FGam42BubQKBwQDRlg4kVVAEI9/2wLtTVQ4R/4Ki
            qTGcENL1rU8IitVSQP0G+J3bTkigj8qpu2jrRyyGs8fXorVXXrY1l+7vJNrPEpCG
            wloQwMw7JVdQ87mqCeIDckoKiwm6W37lkp+aPWJzyBhHasf8Y0i7FrStK9R8vc8C
            /JTInD+Tr7PIxIULaLQ5JVaw9oiCnSMvgchV9u5F+8IBh8vMrNW3rFGK4t6W7tCj
            PnfGjUW8Njsk1ozN9GWvn9EWlAtuTUUcrJRH7MMCgcEAz9oJtev98WgXgrYgXA2M
            8gKYGxR9dIagftJpmYX65naiZBHgu1oLXuGvKEx7exD3iE/SsbK5GXqx7qQ8nVNF
            AkBsajELTAyRJ/5dcyvcQCp0wuSaxq9BM6ZjYnQQjAlr+cZgyZPfjuXfeG9bYDtQ
            /iQFxzb47xhGz8NSFv3ayVnFpuc//VTg2B7cAr5d/4fTMBaIMU+rNFXRAIBvnR89
            +sSjJtkZ5S3wqUm0vpfT4fx6OfKvTK+DazTDqWj1UhiZAoHAXfnUuYHvcQvM/s2I
            sWLv/i39m4YWEo6QqUxepcvqvwkY66lKzu0ZL7WJ//VipCyz0GqIby4r9dMoDHvl
            zSFPY45Fc8dtrxlj+hlSP6ApXg80Yqs6e+PAJumjyrimC/j+TkAocs10grzZ/dm+
            he+jRZOuYP50kEdPUp90E8/agDUgqocNiifhKf/fqQuekr04NfUfFqSXQ100Lzl7
            DrWPbUoED06RUlxCKpR+jJQPasHtXoRgsqkLPxgypxrTGjUVAoHASC6EfqJw3Hh8
            kxwRl3jvHdFz1w5JPrK+j8VuUAXwM/Npaa9GqgFjQ3+QzaIL3uS0xzBgDJ0l5uQE
            a4sL13bbb1kfUkQEUmVkQpjpAUCjqlBeobKEyT3PchXoiUZ0ZCIkfTtT53z1yWnH
            WIx4b2kP8THGS6k7qbjSnWFhP0mideDNEwvULSPgWHV90xJMK9dpaW+LZf0XyOxc
            THBdObizG9Ew6lTPZ4QZ5HVuY9TVDVZ2gpcmemP6VZvuo1L3Neet
            -----END RSA PRIVATE KEY-----

server:
  port: 8889
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}

encrypt:
  key: HolaSoyErwinAlejoGutierrez